export { default as QuizView } from './ui/QuizView.vue'
export { default as PracticeTaskView } from './ui/PracticeTaskView.vue'
export { quizService } from './services/quiz.service'
export { quizState } from './state/quiz.state'
export * from './adapters/quiz.adapter'
